namespace ClaimsAuth.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutogeneratedIdForRole : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.AspNetRoleClaims");
            AlterColumn("dbo.AspNetRoleClaims", "Id", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.AspNetRoleClaims", "Id");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.AspNetRoleClaims");
            AlterColumn("dbo.AspNetRoleClaims", "Id", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.AspNetRoleClaims", "Id");
        }
    }
}
